node {
        stage('Checkout') {
                git url: 'https://github.com/SayantanBan/SpringBootMicroservices.git', credentialsId: 'github-sayantan', branch: 'master'
        }
        stage('Build') { 
            def mvn_version = 'M3'
            withEnv( ["PATH+MAVEN=${tool mvn_version}/bin"] ) {
            dir('discovery-server'){
                  sh 'mvn clean install'
                }
            }
        }
        stage('Test') { 
            // 
        }
        stage('Deploy') { 
            // sh 'mvn install'
        }
    
}
