node {
        stage('Checkout') {
                git url: 'https://github.com/SayantanBan/SpringBootMicroservices.git', credentialsId: 'github-sayantan', branch: 'master'
        }
        stage('Build') { 
            def mvn_version = 'M3'
            withEnv( ["PATH+MAVEN=${tool mvn_version}/bin"] ) {
            dir('discovery-server'){
                  sh 'mvn clean install'
                }
            }
        }
        stage('Image') {
            sh 'docker build github.com/SayantanBan/SpringBootMicroservices/discovery-server'
        }
        stage ('Run') {
            // docker.image("sayantanbanerjee/jenkins_to_docker_discovey_server:${env.version}").run('-p 8761:8761 -h discovery --name discovery')
        }
        stage('Test') { 
            // 
        }
        stage('Deploy') { 
            // sh 'mvn install'
            sh 'docker login -u sayantanbanerjee -p P@ssword@1994'
            sh 'docker push sayantanbanerjee/discovery-server'
        }
    
}
