node {
        stage('Checkout') {
                git url: 'https://github.com/SayantanBan/SpringBootMicroservices.git', credentialsId: 'github-sayantan', branch: 'master'
        }
        stage('Build') { 
            def mvn_version = 'M3'
            withEnv( ["PATH+MAVEN=${tool mvn_version}/bin"] ) {
            dir('discovery-server'){
                  sh 'mvn clean install'
                }
            }
        }
        stage('Test') { 
            def mvn_version = 'M3'
            withEnv( ["PATH+MAVEN=${tool mvn_version}/bin"] ) {
            dir('discovery-server'){
                  sh 'mvn test'
                }
            }        
        }
        stage('Image') {
            sh 'docker build https://github.com/SayantanBan/SpringBootMicroservices.git#master:discovery-server'
        }
        stage('Deploy') { 
            sh 'docker pull sayantanbanerjee/jenkins_to_docker_discovey_server'
            sh 'docker login -u sayantanbanerjee -p P@ssword@1994'
            sh 'docker push sayantanbanerjee/jenkins_to_docker_discovey_server'
        }
        stage ('Run') {
             sh 'docker run sayantanbanerjee/jenkins_to_docker_discovey_server'
        }     
    
}
