//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.12 at 11:55:50 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tk.sayantanbanerjee.currencyconversionsoapservice/jaxb2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package currencyconversionsoapservice.sayantanbanerjee.tk.jaxb2;
